Fix bugs in testbin discovered after it saw real action.
* Avoid race condition in stop_postgres

The github actions environment is much more constrained than my
workstation, and sometimes postgres hasn't finished shutting down when
we try to remove its database directory, so sleep a few times to see if
things will settle down.

* ci mode

Need to chown postgresql dirs after each dpkg action.

Also have deb_start_test explicitly die on errors, as adding the ci
action necessitated making its return value meaningful.

* arm64

Fix string comparison thinko

diff --git a/tools/testbin b/tools/testbin
--- a/tools/testbin
+++ b/tools/testbin
@@ -90,7 +90,7 @@ start_postgres() {
         echo $i...
         sleep 1
     done
-    die "failed to start postgres"
+    die "failed to start postgres $PGVERSION"
 }
 
 # Stop postgres and create a database.
@@ -98,7 +98,12 @@ start_postgres() {
 stop_postgres() {
     eval pid=\$PG${PG_VERSION}PID
     [ -n "$pid" ] && $nop kill $pid
-    $nop rm -rf "$DB"
+    for i in 1 2 3 4 5; do
+        $nop rm -rf "$DB" && return
+        echo "try $i..."
+        sleep 1
+    done
+    die "failed to start postgres $PGVERSION"
 }
 
 start_test() {
@@ -129,15 +134,15 @@ deb_start_test() {
     # we can't test it here.
     [ $FROM_VERSION = 1.10.0-dev ] && return 1
     cmp_version=`cmp_version $FROM_VERSION`
-    [ "$ARCH" -eq arm64 ] && [ $cmp_version -lt $MIN_DEB_ARM ] && return 1
+    [ "$ARCH" = arm64 ] && [ $cmp_version -lt $MIN_DEB_ARM ] && return 1
 
     [ $cmp_version -ge $MIN_DEB_EPOCH ] && EPOCH=1:
     for PG_VERSION in $PG_VERSIONS; do
         select_pg $PG_VERSION
         deb=timescaledb-toolkit-postgresql-${PG_VERSION}=${EPOCH}${FROM_VERSION}~${OS_NAME}${OS_VERSION}
-        $nop sudo apt-get -qq install $deb
+        $nop sudo apt-get -qq install $deb || die
 
-        PATH=/usr/lib/postgresql/$PG_VERSION/bin:$PATH start_test
+        PATH=/usr/lib/postgresql/$PG_VERSION/bin:$PATH start_test || die
     done
 }
 
@@ -164,6 +169,8 @@ test_ci() {
         for PG_VERSION in $PG_VERSIONS; do
             select_pg $PG_VERSION
             $nop sudo dpkg -P timescaledb-toolkit-postgresql-$PG_VERSION
+            # Installing (and possibly uninstalling) toolkit binary gives this back to root but we need to write to it.
+            $nop sudo chown $LOGNAME /usr/lib/postgresql/$PG_VERSION/lib /usr/share/postgresql/$PG_VERSION/extension
             $nop tools/build -pg$PG_VERSION install
 
             finish_test
